CREATE TABLE IF NOT EXISTS Votes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correct BOOLEAN,
    incorrect BOOLEAN,
    CHECK (correct IS NOT NULL OR incorrect IS NOT NULL)
);
